"""tests/conftest.py — pytest configuration and shared regression fixtures.

Path setup
----------
Tests import refactored modules directly from `src/` without a package
prefix (e.g., `from geometry import HybridGeometry`). This file prepends
`src/` to `sys.path` so that style works.

Tolerance tiers for regression testing
--------------------------------------
The regression fixture (tests/regression_data.npz, generated by
scripts/build_regression_fixtures.py) is the ground truth that every
refactored Stage 2 module must reproduce. Two tolerance tiers apply, by
how the array is computed:

- ATOL_ANALYTICAL = 1e-12 — for arrays computed by closed-form formulas
  with no pipeline accumulation. Use for:
      phi1   — analytical biased phase on flat reference (notebook cell 3)
      phi2   — calibration phi2 from analytical tilt-flip (cell 11)
      H_obj  — synthetic Gaussian ground truth (cell 13)
  These should match bit-for-bit under the same formula, modulo
  machine-precision rounding.

- ATOL_PIPELINE = 1e-8 — for arrays produced by floating-point pipeline
  operations (PSI arctan2, np.unwrap, np.polyfit, least-squares). Use for:
      phi1_unwrapped  — recovered unwrapped phase on flat (cell 7)
      phi3_unwrapped  — recovered unwrapped phase on object (cell 17)
      H_rec0          — DC-aligned recovered height (cell 20)
  np.unwrap makes discrete 2 pi decisions and polyfit is a least-squares
  solve; both can shift outputs by O(ULP * condition_number) relative to
  an alternative-but-equivalent implementation. 1e-8 is loose enough to
  absorb that drift, tight enough to catch real refactoring bugs.

Subsequent module tests should import these constants from this file rather
than redeclaring tolerances locally. Example:

    from conftest import ATOL_ANALYTICAL
    np.testing.assert_allclose(phi1_recomputed, regression_data["phi1"],
                               atol=ATOL_ANALYTICAL)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# Tolerance tiers — documented above.
ATOL_ANALYTICAL = 1e-12
ATOL_PIPELINE = 1e-8

FIXTURE_PATH = Path(__file__).parent / "regression_data.npz"


@pytest.fixture(scope="session")
def regression_data() -> dict[str, np.ndarray]:
    """Load the regression fixture as a dict of NumPy arrays.

    Keys: phi1, phi1_unwrapped, phi2, phi3_unwrapped, H_rec0, H_obj.

    Fails the test if the fixture file is missing, with instructions on
    how to regenerate it.
    """
    if not FIXTURE_PATH.exists():
        pytest.fail(
            f"Regression fixture missing: {FIXTURE_PATH}\n"
            f"Generate it via:\n"
            f"    python scripts/build_regression_fixtures.py"
        )
    with np.load(FIXTURE_PATH) as data:
        return {k: data[k].copy() for k in data.files}
