# Physical holder/clamp dimensions in centimeters.
PROJECTOR_HOLDER_OUTER_SIZE_CM = 6.0
PROJECTOR_HOLDER_OUTER_HEIGHT_CM = 3.0
PROJECTOR_HOLDER_INNER_SIZE_CM = 4.2
PROJECTOR_HOLDER_INNER_DROP_CM = 0.8
PROJECTOR_HOLDER_HEIGHT_CM = PROJECTOR_HOLDER_OUTER_HEIGHT_CM

SURFACE_CLAMP_OUTER_CIRCLE_DIAMETER_CM = 5.6
SURFACE_CLAMP_INNER_CIRCLE_DIAMETER_CM = 3.6
SURFACE_CLAMP_TOTAL_HEIGHT_CM = 8.5
SURFACE_CLAMP_BOTTOM_RECT_HEIGHT_CM = 2.51
SURFACE_CLAMP_THICKNESS_CM = 1.0
SURFACE_CLAMP_CIRCLE_CENTER_HEIGHT_CM = 5.3
