PROJECTOR_THROW_RATIO = 1.2
PROJECTOR_IMAGE_ASPECT = 16.0 / 9.0
PROJECTOR_ANGLE_LIMIT_DEG = 45
DEFAULT_PROJECTION_ANGLE_DEG = -20.0
DEFAULT_DEVICE_SPACING_CM = 12.0
PROJECTOR_LENS_WINDOW_WIDTH_CM = 1.4
PROJECTOR_LENS_WINDOW_HEIGHT_CM = 1.0
PROJECTOR_LENS_FACE_EPS = 0.01

# World-space dimensions are centimeters. The camera model uses the
# BFS-U3-13Y3M-C / Sony IMX304 native sensor geometry for aspect and field
# mapping, while default captures use a 4x downsampled grid for interactive
# simulation performance.
OPTICAL_AXIS_HEIGHT_CM = 8.1
PROJECTOR_LENS_HEIGHT_CM = OPTICAL_AXIS_HEIGHT_CM
SURFACE_CAMERA_LENS_HEIGHT_CM = OPTICAL_AXIS_HEIGHT_CM
TELECENTRIC_LENS_DIAMETER_CM = 10.0
TELECENTRIC_LENS_TO_CAMERA_LENS_CM = 4.0
SURFACE_CAMERA_REAR_LENS_DIAMETER_CM = 1.6
SURFACE_CAMERA_MODEL = "Teledyne FLIR Blackfly S BFS-U3-13Y3M-C"
SURFACE_CAMERA_SENSOR_MODEL = "Sony IMX304"
SURFACE_CAMERA_SENSOR_WIDTH_PX = 4112
SURFACE_CAMERA_SENSOR_HEIGHT_PX = 3008
SURFACE_CAMERA_PIXEL_PITCH_UM = 3.45
SURFACE_CAMERA_SENSOR_WIDTH_MM = 14.1864
SURFACE_CAMERA_SENSOR_HEIGHT_MM = 10.3776
SURFACE_CAMERA_CAPTURE_WIDTH_PX = SURFACE_CAMERA_SENSOR_WIDTH_PX // 4
SURFACE_CAMERA_CAPTURE_HEIGHT_PX = SURFACE_CAMERA_SENSOR_HEIGHT_PX // 4
PROJECTOR_RAYCAST_COLUMNS = 12
PROJECTOR_RAYCAST_ROWS = 8
PROJECTOR_RAYCAST_EDGE_SUBDIVISIONS = 2
MINIMAP_RAYCAST_COLUMNS = 6
MINIMAP_RAYCAST_ROWS = 4
MINIMAP_RAYCAST_EDGE_SUBDIVISIONS = 1
FIELD_OBJECT_PLANE_GAP_M = 0.2
SWEEP_RECORD_FRAMES = 60
SWEEP_RECORD_FPS = 20.0
SWEEP_RECORD_WIDTH = SURFACE_CAMERA_CAPTURE_WIDTH_PX
SWEEP_RECORD_HEIGHT = SURFACE_CAMERA_CAPTURE_HEIGHT_PX
SWEEP_RECORD_PHASE_SPAN_DEG = 360.0
